begin;

alter table public.cases
  add column if not exists source_url text,
  add column if not exists source_like_count int,
  add column if not exists source_comment_count int,
  add column if not exists source_share_count int,
  add column if not exists source_save_count int,
  add column if not exists source_published_at timestamptz,
  add column if not exists source_metrics_captured_at timestamptz,
  add column if not exists evidence_level text not null default 'L0',
  add column if not exists tags text[] not null default '{}'::text[];

alter table public.case_candidates
  add column if not exists source_url text,
  add column if not exists source_like_count int,
  add column if not exists source_comment_count int,
  add column if not exists source_share_count int,
  add column if not exists source_save_count int,
  add column if not exists source_published_at timestamptz,
  add column if not exists source_metrics_captured_at timestamptz,
  add column if not exists evidence_level text not null default 'L0',
  add column if not exists tags text[] not null default '{}'::text[];

alter table public.cases
  add column if not exists source_candidate_id uuid
    references public.case_candidates(id) on delete set null;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'cases_evidence_level_check'
  ) then
    alter table public.cases
      add constraint cases_evidence_level_check
      check (evidence_level in ('L0', 'L1', 'L2'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'case_candidates_evidence_level_check'
  ) then
    alter table public.case_candidates
      add constraint case_candidates_evidence_level_check
      check (evidence_level in ('L0', 'L1', 'L2'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'cases_source_metrics_nonnegative_check'
  ) then
    alter table public.cases
      add constraint cases_source_metrics_nonnegative_check
      check (
        (source_like_count is null or source_like_count >= 0)
        and (source_comment_count is null or source_comment_count >= 0)
        and (source_share_count is null or source_share_count >= 0)
        and (source_save_count is null or source_save_count >= 0)
      );
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'case_candidates_source_metrics_nonnegative_check'
  ) then
    alter table public.case_candidates
      add constraint case_candidates_source_metrics_nonnegative_check
      check (
        (source_like_count is null or source_like_count >= 0)
        and (source_comment_count is null or source_comment_count >= 0)
        and (source_share_count is null or source_share_count >= 0)
        and (source_save_count is null or source_save_count >= 0)
      );
  end if;
end
$$;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  path text not null,
  referrer text,
  anonymous_session_id text not null,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.feedback_messages (
  id uuid primary key default gen_random_uuid(),
  kind text not null,
  message text not null,
  contact text,
  page text,
  status text not null default 'open',
  created_at timestamptz not null default now()
);

create index if not exists idx_analytics_events_name_created_at
  on public.analytics_events(event_name, created_at desc);
create unique index if not exists idx_cases_source_candidate_id
  on public.cases(source_candidate_id)
  where source_candidate_id is not null;
create index if not exists idx_feedback_messages_status_created_at
  on public.feedback_messages(status, created_at desc);

alter table public.analytics_events enable row level security;
alter table public.feedback_messages enable row level security;

commit;
