-- 无账号的投票 / 点赞：一张表管两种反应。
--
-- 设计依据
-- --------
-- 1) 站点没有账号系统，也不打算做。所以身份只能是"浏览器"，不是"用户"。
--    这里用埋点那套匿名会话 ID（analytics_events.anonymous_session_id 同源，
--    前端生成逻辑在 src/lib/anonymous-session.ts，不另造一套）当身份键。
--
-- 2) 防重范围 = (case_slug, session_id, kind)：同一浏览器会话对同一案例的每种反应
--    只算一次。这是刻意的弱防重——匿名场景下没有比它更强又不侵犯隐私的选择：
--    不存 IP、不存指纹、不种额外 cookie。换浏览器、清缓存、开无痕都能再投一次，
--    接受这个上限；它拦的是误触和连点，不是有组织刷票。
--    真要防刷得等到有账号或引入验证码，那是另一个决定。
--
-- 3) 一张表两种 kind，而不是 likes / votes 两张表：两者的形状完全一样
--    （谁 + 哪条案例 + 什么时候），聚合查询也想一次拿完。加第三种反应时
--    只需要动 check 约束，不用再开一张表和一套 RLS。
--
-- 4) 为什么不复用 2026-04 遗留的 public.case_likes：
--    那张表是账号路线的产物，主键是 (case_id uuid, user_id uuid)，user_id 带
--    references auth.users 外键。匿名会话根本填不进去这个键，改造它等于换掉主键、
--    换掉外键、换掉全部 RLS policy，剩下的只有表名。它前端从来没接过，数据是空的，
--    留着当历史记录，本迁移一个字都不动它。
--
-- 5) 引用案例用 slug 而不是 cases.id 外键：反应是纯展示数据，允许指向一条还没
--    发布 / 已经下架的 slug（下架期间计数照常累计，重新上架就还在）。
--    加外键会让下架动作被反应行卡住，收益不值这个耦合。
--    代价是可能存在指向不存在 slug 的孤儿行，由 API 层只按已知 slug 查询兜住。
--
-- 6) RLS 开着但一条 policy 都不给 anon / authenticated：读写全部走服务端
--    API route（src/app/api/reactions/route.ts）用 service role key。
--    浏览器直连 Supabase 拿不到这张表的任何权限，写入必须经过服务端的
--    slug / kind / sessionId 校验，客户端伪造不了别人的 session_id 去刷别人的票
--    （它仍然能伪造自己的，见第 2 条）。

create table if not exists public.case_reactions (
  id bigint generated by default as identity primary key,
  case_slug text not null,
  session_id text not null,
  kind text not null check (kind in ('like', 'retest_vote')),
  created_at timestamptz not null default now()
);

comment on table public.case_reactions is
  '匿名反应（点赞 / 催复测投票）。身份是浏览器会话不是用户；读写只走服务端 service role。';
comment on column public.case_reactions.case_slug is
  '对应 cases.slug。刻意不加外键，允许指向未发布或已下架的 slug。';
comment on column public.case_reactions.session_id is
  '匿名会话 ID，与 analytics_events.anonymous_session_id 同源。';

-- 防重：同一会话 + 同一案例 + 同一种反应只留一行。
-- 用唯一索引而不是 unique constraint，是为了能带 if not exists 重复执行。
create unique index if not exists case_reactions_session_kind_key
  on public.case_reactions (case_slug, session_id, kind);

-- 主查询是"按 slug 取这条案例的全部反应，在应用层分 kind 计数"，
-- (case_slug, kind) 这个顺序能同时服务单 slug 查询和 slug in (...) 的批量查询，
-- 且把同一 slug 的行按 kind 聚在一起，扫描更紧凑。
create index if not exists case_reactions_slug_kind_idx
  on public.case_reactions (case_slug, kind);

alter table public.case_reactions enable row level security;

-- 这里一条 policy 都不建，是故意的，不是漏写。
-- RLS 开启且无 policy 时，anon 和 authenticated 的任何 select/insert/delete 都返回空 / 被拒；
-- service role 绕过 RLS，所以服务端 API route 照常工作。
--
-- 再显式收一次表级权限：Supabase 默认会把新表的权限授给 anon / authenticated，
-- 万一以后有人手滑 `alter table ... disable row level security`，光靠 RLS 就没了兜底。
-- 代价是将来真想开只读直连时，除了加 policy 还得把 select 权限 grant 回来——
-- 这一步是故意留成"必须显式做"的，别顺手加 insert/delete，
-- 那等于把防重校验交给客户端。
revoke all on public.case_reactions from anon;
revoke all on public.case_reactions from authenticated;
