-- Agent API 的 key 与用量：把公开接口从"完全开放"变成"匿名可用 + 带 key 有配额"。
--
-- 设计依据
-- --------
-- 1) 为什么不复用账号体系：站点明确不建账号（见 AGENTS.md 当前认证状态）。
--    API key 的持有者是"一个调用方程序"，不是"一个用户"，这两件事本来就不该
--    是同一张表。v1 的签发是运营手动跑 scripts/api-keys/issue.mjs，
--    没有自助注册，也就不需要用户、邮箱、密码里的任何一样。
--
-- 2) 只存 hash 不存明文：明文只在签发那一刻出现在运营的终端里，之后库里、
--    日志里、备份里都没有它。运营弄丢了就重发一把新的，这是刻意的单向设计——
--    "能找回明文"和"泄库不等于泄密"不可兼得，选后者。
--    用 sha-256 而不是 bcrypt / argon2：key 是 192 bit 的高熵随机串，不是人选的密码，
--    没有字典攻击面，慢哈希在这里只换来每次请求几十毫秒的延迟，不换任何安全性。
--
-- 3) 用量按天一行 upsert，不是一请求一行：
--    一请求一行意味着按当前免费流量就能每天写进几万行，一个月后这张表比 cases
--    大两个数量级，而我们从它身上唯一要读的东西是"今天这把 key 用了多少次"。
--    按 (key, date) 聚合成一行，读是主键点查，写是一次 update，表的大小
--    等于 key 数 × 天数。真需要逐请求明细时那是可观测性问题，该走日志不该走主库。
--
-- 4) 为什么要 consume_api_quota 这个函数而不是在应用层 select-then-update：
--    读改写有竞态。同一把 key 的并发请求会读到同一个旧值，各自 +1 写回去，
--    计数少算，超额也放得过去。配额只要不精确就等于没有配额。
--    函数里用 for update 行级锁把「读 → 判 → 写」做成一个原子操作，
--    并且把限额判断也放进去——判断和扣减必须在同一个锁里，分开做等于没锁。
--
-- 5) RLS 全锁死、一条 policy 都不给，风格照 20260805200000_case_reactions.sql：
--    读写只走服务端 service role。浏览器直连 Supabase 拿不到这两张表的任何权限，
--    key 的 hash 和用量都不该出现在任何客户端可达的地方。
--
-- 6) 表不存在时应用层降级为免 key 模式（src/app/api/public/_lib/api-access.ts），
--    所以这份迁移可以在代码上线之后再跑，中间窗口里 API 照常工作。

-- ---------------------------------------------------------------------------
-- api_keys
-- ---------------------------------------------------------------------------

create table if not exists public.api_keys (
  id bigint generated by default as identity primary key,
  key_hash text not null unique,
  name text not null,
  daily_limit integer not null default 2000,
  status text not null default 'active',
  note text,
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  last_used_at timestamptz,
  constraint api_keys_key_hash_shape_check
    check (key_hash ~ '^[0-9a-f]{64}$'),
  constraint api_keys_name_not_blank_check
    check (length(btrim(name)) between 1 and 80),
  constraint api_keys_daily_limit_range_check
    check (daily_limit between 1 and 1000000),
  constraint api_keys_status_check
    check (status in ('active', 'revoked')),
  -- 吊销必须留下时间：没有吊销时间的 revoked 行事后无法回答"什么时候停的"。
  constraint api_keys_revoked_at_check
    check ((status = 'revoked') = (revoked_at is not null))
);

comment on table public.api_keys is
  'Agent API key。只存 sha-256 hash，明文只在签发时打印一次；读写只走服务端 service role。';
comment on column public.api_keys.key_hash is
  '明文 key（gc_ 前缀 + hex 随机串）的 sha-256 十六进制摘要。唯一。';
comment on column public.api_keys.name is
  '运营备注名，用于事后认领和吊销。不参与任何鉴权逻辑。';
comment on column public.api_keys.daily_limit is
  '每 UTC 自然日的请求上限，由 consume_api_quota 强制执行。';
comment on column public.api_keys.last_used_at is
  '当日首次调用时更新一次，不是每请求更新——只为回答"这把 key 还活着吗"。';

-- 唯一约束已经建了索引，验证路径的 where key_hash = $1 直接命中，不用再加。
-- 这个部分索引服务的是运营视角的"列出还在用的 key"。
create index if not exists api_keys_active_idx
  on public.api_keys (created_at desc)
  where status = 'active';

alter table public.api_keys enable row level security;

-- 一条 policy 都不建，是故意的。RLS 开启且无 policy 时 anon / authenticated
-- 的任何操作都被拒；service role 绕过 RLS，服务端照常工作。
-- 再显式收一次表级权限，防止将来有人手滑 disable row level security 之后失去兜底。
revoke all on public.api_keys from anon;
revoke all on public.api_keys from authenticated;

-- ---------------------------------------------------------------------------
-- api_usage
-- ---------------------------------------------------------------------------

create table if not exists public.api_usage (
  api_key_id bigint not null
    references public.api_keys (id) on delete cascade,
  usage_date date not null,
  request_count integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (api_key_id, usage_date),
  constraint api_usage_request_count_check check (request_count >= 0)
);

comment on table public.api_usage is
  '按 (key, UTC 日期) 聚合的调用计数，一天一行 upsert。不是逐请求明细表。';
comment on column public.api_usage.usage_date is
  'UTC 自然日。刻意不用本地时区——函数跑在哪个区域不确定，UTC 是唯一一致的切分。';

-- 这里和 case_reactions 的取舍相反：那张表刻意不加外键（反应要能指向已下架的 slug），
-- 这张表必须加，而且要 on delete cascade——用量行脱离 key 之后没有任何意义，
-- 删 key 时留着它只是垃圾。

-- 运营视角的"最近谁在用"。主键已经覆盖了按 key 查当日用量的路径。
create index if not exists api_usage_date_idx
  on public.api_usage (usage_date desc);

alter table public.api_usage enable row level security;
revoke all on public.api_usage from anon;
revoke all on public.api_usage from authenticated;

-- ---------------------------------------------------------------------------
-- consume_api_quota：原子的「查用量 → 判限额 → 计数 +1」
-- ---------------------------------------------------------------------------
--
-- 返回 (allowed, used)：
--   allowed = false 时不计数，used 是当前已用量（此时 used >= p_limit）。
--   allowed = true  时 used 是**计数之后**的值，应用层据此算 remaining = limit - used。
--   所以 limit = 100 时，第 100 次调用返回 (true, 100)、remaining = 0，第 101 次返回 (false, 100)。

create or replace function public.consume_api_quota(
  p_key_id bigint,
  p_day date,
  p_limit integer
)
returns table (allowed boolean, used integer)
language plpgsql
volatile
security definer
set search_path = public, pg_temp
as $$
declare
  v_used integer;
  v_fresh boolean := false;
begin
  -- 先保证今天这一行存在。并发下只有一个事务能插入成功，其余走 do nothing，
  -- 随后统一由下面的 for update 拿锁读值，两条路径汇合。
  insert into public.api_usage (api_key_id, usage_date, request_count)
  values (p_key_id, p_day, 0)
  on conflict (api_key_id, usage_date) do nothing;

  -- for update：从这里到 commit，这把 key 今天的行被独占。
  -- 判断和扣减必须在同一个锁区间内，这是整个函数存在的唯一理由。
  select request_count into v_used
    from public.api_usage
   where api_key_id = p_key_id
     and usage_date = p_day
   for update;

  if v_used is null then
    -- 理论上不可达（上面刚保证了行存在），但真发生了就当配额用尽拒绝，
    -- 而不是当作 0 放行——不确定的时候倾向于拒绝，别把配额漏出去。
    return query select false, p_limit;
    return;
  end if;

  if v_used >= p_limit then
    return query select false, v_used;
    return;
  end if;

  v_fresh := (v_used = 0);

  update public.api_usage
     set request_count = request_count + 1,
         updated_at = now()
   where api_key_id = p_key_id
     and usage_date = p_day
  returning request_count into v_used;

  -- last_used_at 只在当日首次调用时写一次。每请求都写的话，这一行会成为
  -- 每次调用都要更新的热行，白白制造行版本和 vacuum 压力，
  -- 而它要回答的问题（这把 key 还活着吗）精确到天就够了。
  if v_fresh then
    update public.api_keys
       set last_used_at = now()
     where id = p_key_id;
  end if;

  return query select true, v_used;
end;
$$;

comment on function public.consume_api_quota(bigint, date, integer) is
  '原子地判限额并计数 +1。security definer + RLS 全锁，只允许 service role 调用。';

-- security definer 的函数默认对 public 可执行，必须显式收回：
-- 否则 anon 能直接 rpc 调它去消耗别人的配额（虽然拿不到 key，但能猜 id 刷计数）。
revoke all on function public.consume_api_quota(bigint, date, integer) from public;
revoke all on function public.consume_api_quota(bigint, date, integer) from anon;
revoke all on function public.consume_api_quota(bigint, date, integer) from authenticated;
