-- 复测记录：一条案例的 prompt 在某一天被重跑了一次，产物在哪儿，人判成什么。
--
-- 设计依据
-- --------
-- 1) 这张表存的是**证据**，不是**结论**。
--    复测脚本（scripts/retest/run-retest.mjs）只往里写 case_slug / tested_at /
--    model / artifact_url——「谁在什么时候用什么模型跑出了这个东西」。
--    verdict 和 notes 一律留 null，等人看过对照图再填。
--    脚本永远不写 verdict，也永远不碰 cases.stability_score：
--    自动判定图像「像不像」这件事本身就是我们不信任的东西，
--    真让脚本填了，站上的稳定分就变成模型自评，那这份数据也就不值钱了。
--
-- 2) 一条案例可以有多行，不做唯一约束。
--    复测的价值恰恰在时间序列上：同一段 prompt 半年前能跑出来、现在跑不出来，
--    这个变化才是「稳定榜」要展示的东西。加唯一键等于只留最后一次，把历史抹了。
--    同一天跑两次也允许——重跑一般是因为第一次的产物有问题，
--    留着两行让人能看出「换了个跑法」，比悄悄覆盖强。
--
-- 3) 引用案例用 slug 而不是 cases.id 外键：和 case_reactions 同一个理由。
--    复测结果要允许指向一条已经下架的 slug——恰恰是「复现不出来了」的案例
--    最可能被下架，如果外键把这行卡住，我们就丢掉了下架的证据。
--    代价是可能出现指向不存在 slug 的孤儿行，由查询层只按已知 slug 取数兜住。
--
-- 4) artifact_url 存 Vercel Blob 的公开 URL（retests/<slug>/<date>-regen.png）。
--    不存 base64、不存本地路径：本地路径换台机器就没了，base64 会让这张表
--    在几十条之后就没法全表扫。Blob 上那份是唯一权威副本。
--    本地 tmp/retest-artifacts/ 里的原图 + 复现图属于跑完就能删的中间产物。
--
-- 5) verdict 用自由文本加 check 约束，而不是 enum 类型。
--    v1 还不知道人审到底会分出几档（现在的预期是 reproduced / degraded / failed，
--    但很可能会冒出「prompt 得改了才行」这种第四档）。
--    check 约束改起来是一条 alter，pg enum 加值要小心得多。
--    先留松，等真跑过几轮人审再收紧。
--
-- 6) operator 可空：v1 是一个人跑一个人审，填不填没区别。
--    留这个列是因为一旦开始有第二个人参与判定，
--    「这条是谁判的」会立刻变成必须能回答的问题，那时候再加列就要补历史数据。

create table if not exists public.case_retests (
  id bigint generated by default as identity primary key,
  case_slug text not null,
  tested_at timestamptz not null default now(),
  model text not null,
  artifact_url text,
  verdict text check (verdict is null or verdict in ('reproduced', 'degraded', 'failed', 'inconclusive')),
  notes text,
  operator text,
  created_at timestamptz not null default now()
);

comment on table public.case_retests is
  '复测证据。脚本只写产物，verdict / notes 由人填；本表不驱动 cases.stability_score 自动更新。';
comment on column public.case_retests.case_slug is
  '对应 cases.slug。刻意不加外键，允许指向已下架的 slug——复现失败的案例最可能被下架。';
comment on column public.case_retests.model is
  '实际跑复测的模型标识，例如 codex-builtin-image-generation / gpt-5.6-sol。同一条案例换模型重测要另起一行。';
comment on column public.case_retests.artifact_url is
  'Vercel Blob 上的复现产物公开 URL。为空表示这次复测没拿到产物（模型拒绝 / 超时），这本身也是证据。';
comment on column public.case_retests.verdict is
  '人审结论，脚本永远写 null。收敛出稳定档位之前先用 check 约束而不是 enum。';

-- 主查询是「按 slug 取这条案例的全部复测记录，按时间倒序展示」。
-- (case_slug, tested_at desc) 这个顺序能一次服务单 slug 详情和 slug in (...) 的批量取数，
-- 且直接给出排好序的结果，不用再排一次。
create index if not exists case_retests_slug_tested_at_idx
  on public.case_retests (case_slug, tested_at desc);

alter table public.case_retests enable row level security;

-- 和 case_reactions 一样：一条 policy 都不建，是故意的。
-- RLS 开启且无 policy 时 anon / authenticated 读写全被拒；service role 绕过 RLS，
-- 所以服务端脚本和 API route 照常工作。
--
-- 再显式收一次表级权限，兜住「有人手滑 disable row level security」的情况。
-- 将来真要在前端直连读复测记录，除了加 select policy 还得把 select 权限 grant 回来——
-- 这一步故意留成必须显式做的动作。别顺手 grant insert/update：
-- 那等于把「这条案例复现成功了」的判定权交给浏览器。
revoke all on public.case_retests from anon;
revoke all on public.case_retests from authenticated;
